version: '3'
services:
  xonox-back:
    build:
      context: ./xonox
      dockerfile: Dockerfile
    volumes:
      - ./xonox.conf:/usr/src/app/xonox.conf
    networks:
      - default
    restart: always
  xonox-front:
    build:
      context: ./xonox-frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - xonox-back
    restart: always
networks:
  default:
